HTTP/1.1 200 OK
Content-Type: application/json
Cache-Control: no-store
Pragma: no-cache
Content-Length: 748

{
  "access_token": "example-access-token-01",
  "token_type": "Bearer",
  "expires_in": 600,
  "scope": "openid read",
  "id_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImxlY3R1cmUtcnNhLTAxIn0.eyJpc3MiOiJodHRwczovL2F1dGguZXhhbXBsZSIsInN1YiI6ImFsaWNlIiwiYXVkIjoiY2hhdC12aWV3ZXIiLCJpYXQiOjE3ODk4NjI0MDAsImV4cCI6MTc4OTg2MzAwMCwiYXV0aF90aW1lIjoxNzg5ODYyMzQwLCJub25jZSI6ImV4YW1wbGUtbm9uY2UtMDEifQ.eTqN9IMLk9eOD_J7zFKHFFC7V7fcp2E3-hXOXeCgE-PFjdhy8IWPGNSVuaugsLq0v0Hihlwg2awpMEQLAHqJ0ntuAurNZJJNe1kjfTsbn2HqHGnPIpMIoA3vwLvrbzO_EHLtoPAZV4jeD5irPWOvxgmc2H1RzT2kiIPqwFF5vqlbg0cJuora9heaeNZuy5bZdMAi19hNlEVIoqq9A6E2sDrV1ZJJR_-7X_VQh26FpAiylWoIm4NxCBg5BHtOLgO6SdxAeRN2xm2p_-gG8BJz1H-HvD3eVG_qQ9MHqg9oA7fh9Hm9KgqhL5-OH24JLHXzPiMdy06xdvjoH6UsDfVuMg"
}
